OBJECT_FILES = libskein_ubi.o

all:	$(OBJECT_FILES)
	gcc $(LDFLAGS) -shared -o libskein.dll $(OBJECT_FILES)

libskein_ubi.o:	libskein_ubi.c libskein_ubi.h
	gcc $(CFLAGS) -Wall -Wconversion -Werror -Wextra -c -o \
	libskein_ubi.o libskein_ubi.c

clean:
	del /f *.o libskein.so

library: $(OBJECT_FILES)
	gcc $(LDFLAGS) -shared -o libskein.dll $(OBJECT_FILES)

purge:
	del /f *~*
